[package]
name = "rusty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-client = "1.10.5"
solana-program = "1.10.5"
solana-sdk = "1.10.5"
solana-system-program = "1.10.5"
